### ISSUE TITLE
Compiling Issues Arduino Library

### ISSUE THREAD

**Issue by jeylites** [washcroft/HttpGarageDoorController#15]
@washcroft 

I hope all is well during these uncharted times.  I needed to change my Wemos D1 earlier today, tried to compile only to run into some errors. 

It seems that there's an incompatibility issue with ArduinoJson library. So I downgraded to ver.5 which has to lead me to another problem with WifiHelper

**ArduinoJson Issue**

```
HttpGarageDoorController:146:11: error: StaticJsonBuffer is a class from ArduinoJson 5. Please see arduinojson.org/upgrade to learn how to upgrade your program to ArduinoJson version 6
   StaticJsonBuffer<200> jsonBuffer;
           ^
exit status 1
StaticJsonBuffer is a class from ArduinoJson 5. Please see arduinojson.org/upgrade to learn how to upgrade your program to ArduinoJson version 6

```

**Wifihelper Issue**

```

sketch/src/WiFiHelper/WiFiHelper.cpp: In member function 'bool WiFiHelper::connect()':
sketch/src/WiFiHelper/WiFiHelper.cpp:202:23: error: ambiguous overload for 'operator!=' (operand types are 'wl_status_t' and 'const IPAddress')
     if (WiFi.status() != INADDR_NONE) {

                       ^
sketch/src/WiFiHelper/WiFiHelper.cpp:202:23: note: candidates are:
sketch/src/WiFiHelper/WiFiHelper.cpp:202:23: note: operator!=(int, uint32_t {aka unsigned int}) <built-in>
sketch/src/WiFiHelper/WiFiHelper.cpp:202:23: note: operator!=(int, u32_t {aka long unsigned int}) <built-in>
sketch/src/WiFiHelper/WiFiHelper.cpp:202:23: note: operator!=(int, int) <built-in>
exit status 1
Error compiling for board LOLIN(WEMOS) D1 R2 & mini.
```

**Comment by jeylites** [comment]
@washcroft 

I was able to recompile based on the following version but it would be nice to have an updated version. 

WifiHelper issue was due to the ESP Board Version. Only works on 2.4.2, anything above would give an error.

ARDUINO LIBRARY 

HttpGarageDoorController
HTTP Controller Firmware Version 2.0.0

Arduino Library
ArduinoJson Version 5.10.1
Arduino OTA Version 1.0.7
Wifi101 Version 0.11.0
Wifi 101 OTA Version 1.0.1

Board Manager
ESP8266 Version 2.4.0 (Compile issue anything above 2.4.0)
Arduino AVR 1.6.9
Lolin Wemos D1 Mini

Arduino Compiler
Version 1.8.12 MacOsx

**Comment by jeylites** [comment]
@washcroft 

Hello, just checking in....

**Comment by jeylites** [comment]
Hello, Any thoughts on updating this lovely project? I still can't get it to work with my garage door. :(

**Comment by lagunacomputer** [comment]
> [@washcroft](https://github.com/washcroft)
> 
> I was able to recompile based on the following version but it would be nice to have an updated version.
> 
> WifiHelper issue was due to the ESP Board Version. Only works on 2.4.2, anything above would give an error.
> 
> ARDUINO LIBRARY
> 
> HttpGarageDoorController HTTP Controller Firmware Version 2.0.0
> 
> Arduino Library ArduinoJson Version 5.10.1 Arduino OTA Version 1.0.7 Wifi101 Version 0.11.0 Wifi 101 OTA Version 1.0.1
> 
> Board Manager ESP8266 Version 2.4.0 (Compile issue anything above 2.4.0) Arduino AVR 1.6.9 Lolin Wemos D1 Mini
> 
> Arduino Compiler Version 1.8.12 MacOsx


My old esp8266 finally died and I was trying to flash a new module to replace it.

I was able to get it to compile using the awesome tips about the library versions above, however the esp8266 just hangs now.
Seems to die right about the time Serial.start starts outputting log messages if logging set to anything above 0.  On my various NodeMCU's and Wemos clones, it looks like Wifi is just not initializing or connecting, and thus hanging.  Probably something to do with the wifi library used for the 8266 no longer works.

Would be eternally grateful if someone could figure out why this code wont work anymore even if you can get it to compile and flash.  Thx

**Comment by lagunacomputer** [comment]
Nevermind, I got it working again.
